### ISSUE TITLE
Completar página "Sobre" e criar página sobre os "Membros"

### ISSUE THREAD

**Issue by takusuman** [vit0rr/website-moderno#2]
O texto do sobre é esse:
> O Pindorama é um projeto que produz software LIVRE e inteligente, seguindo os princípios de modularidade, simplicidade e sanidade.
Começou (e ainda é) algo pessoal e hobístico de um grupo de amigos, que iniciaram o projeto lá por volta do final de Junho de 2019.
Buscamos manter sanidade e competência como um projeto de código-aberto brasileiro.

A parte do "grupo de amigos" poderia ser linkada à página de membros, que apenas listaria os nomes e suas funções.
Exemplo:
> Fulano de Tal
> - Artista e mantenedor secundário do servidor

É só isso mesmo. 🤷🏽‍♂️

**Comment by vit0rr** [comment]
Discordo de criar uma página apenas para listar o Grupo de Amigos. Considero viável, adicionar esse texto do sobre na seção de Sobre já existente no final da página e colocar os membros naquela listagem que está de baixo do texto "Magnam dolores..."
![example](https://user-images.githubusercontent.com/70543018/134807725-703c7cd9-7269-41cf-b27b-6ef7815a2a46.png)

**Comment by takusuman** [comment]
Pode ser
